#!/usr/bin/env python
# https://unix.stackexchange.com/a/12483
import copy, sys
from pyPdf import PdfFileWriter, PdfFileReader

input = PdfFileReader(sys.stdin)
output = PdfFileWriter()
for p in [input.getPage(i) for i in range(0,input.getNumPages())]:
    q = copy.copy(p)
    (w, h) = p.mediaBox.upperRight

    if w > h:
        p.mediaBox.upperRight = (w / 2, h)
        q.mediaBox.upperLeft = (w / 2, h)
    else:
        p.mediaBox.upperRight = (w, h / 2)
        q.mediaBox.upperLeft = (w, h / 2)

    output.addPage(p)
    output.addPage(q)
output.write(sys.stdout)
