#!/usr/bin/env python
from __future__ import print_function
import copy, sys
from pyPdf import PdfFileWriter, PdfFileReader

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

if len(sys.argv) < 4:
    eprint("Need > 2 arguments, but only got %d" % (len(sys.argv) - 1))
    sys.exit(1)

input_file = sys.argv[1]
output_file = sys.argv[2]

# provide the real page numbers as found in the PDF as additional command line args.
# The cover page should be -1; the next one is 0, then 1, and so on.
indices = sys.argv[3:]

input = PdfFileReader(open(input_file, "rb"))
output = PdfFileWriter()

for i in range(-1, len(indices) - 1):
    page_number = indices.index(str(i))
    eprint("Adding old page %d as new #%d" % (page_number, i + 2))

    try:
        output.addPage(input.getPage(page_number))
    except IndexError:
        eprint("Could not find page %d" % (page_number))

output.write(file(output_file, "wb"))
